// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200403170909");
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.startupRolloutPrefs.app.normandy.onsync_skew_sec", 3300);
user_pref("app.normandy.startupRolloutPrefs.layout.css.serialize-grid-implicit-tracks", true);
user_pref("app.normandy.user_id", "6843762f-eda1-43eb-851a-8e5808bc1d58");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1588332638);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1588332613);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1588332758);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1588332668);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 2843);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1588332607);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 92);
user_pref("browser.newtabpage.activity-stream.impressionId", "{39b478a1-607a-4429-8894-de9099dc0cc4}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1588332633075");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1588334404075");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1588332612209");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1588336212209");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.slowStartup.averageTime", 7011);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200403170909");
user_pref("browser.startup.homepage_override.mstone", "75.0");
user_pref("browser.startup.lastColdStartupCheck", 1588332609);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1588332610569");
user_pref("distribution.iniFile.exists.appversion", "75.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "adb3f761b7eb4b188346a9724032604a");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "75.0");
user_pref("extensions.lastPlatformVersion", "75.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"8fe92ea5-9bb3-4216-ad51-cbc6671620a8\",\"formautofill@mozilla.org\":\"1e157b88-9884-4ad0-952d-da080e81520a\",\"screenshots@mozilla.org\":\"b871300f-951e-4f8d-88c5-e08958325f7a\",\"webcompat-reporter@mozilla.org\":\"b1e12f3a-516c-457f-8ab2-aae3057264f8\",\"webcompat@mozilla.org\":\"5a2dcd77-38eb-4e4d-8c04-a0c64613cf0c\",\"default-theme@mozilla.org\":\"ca6322d6-9f40-49e5-8134-e08f4a883027\",\"google@search.mozilla.org\":\"92f5aebd-eabe-45eb-937a-1146106cec09\",\"amazondotcom@search.mozilla.org\":\"388c5008-69b9-4a2e-a6f4-47b081dc830b\",\"bing@search.mozilla.org\":\"736961bf-1536-4c61-93b1-0de57aed856d\",\"ddg@search.mozilla.org\":\"f1541c94-e858-4540-83ef-4f2e6f0026f3\",\"ebay@search.mozilla.org\":\"3f299531-e670-4c69-b08a-2c32429790a8\",\"twitter@search.mozilla.org\":\"69885f50-ca0d-4b90-b862-e6e6adf222a1\",\"wikipedia@search.mozilla.org\":\"846c235b-53e3-4df9-a75a-2af6fc2e0251\"}");
user_pref("gfx.crash-guard.status.wmfvpxvideo", 2);
user_pref("gfx.crash-guard.wmfvpxvideo.appVersion", "75.0");
user_pref("gfx.crash-guard.wmfvpxvideo.deviceID", "0x3ea0");
user_pref("gfx.crash-guard.wmfvpxvideo.driverVersion", "25.20.100.6577");
user_pref("layers.mlgpu.sanity-test-failed", false);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.advanced-layers", true);
user_pref("sanity-test.device-id", "0x3ea0");
user_pref("sanity-test.driver-version", "25.20.100.6577");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20200403170909");
user_pref("sanity-test.webrender.force-disabled", false);
user_pref("security.sandbox.content.tempDirSuffix", "{33534d10-e617-4e64-a734-034fa741be50}");
user_pref("security.sandbox.plugin.tempDirSuffix", "{d6f33b85-8ee2-46fc-b335-57a0fa256e7f}");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1588332601);
user_pref("toolkit.telemetry.cachedClientID", "d94fd1a9-313c-4382-b753-e555ea8b1864");
user_pref("toolkit.telemetry.previousBuildID", "20200403170909");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
