# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppMainWindow(object):
    def setupUi(self, AppMainWindow):
        AppMainWindow.setObjectName("AppMainWindow")
        AppMainWindow.resize(1200, 600)
        AppMainWindow.setMinimumSize(QtCore.QSize(1173, 528))
        self.centralwidget = QtWidgets.QWidget(AppMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stats_layout = QtWidgets.QFormLayout()
        self.stats_layout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.stats_layout.setContentsMargins(10, 10, 10, 10)
        self.stats_layout.setHorizontalSpacing(10)
        self.stats_layout.setVerticalSpacing(5)
        self.stats_layout.setObjectName("stats_layout")
        self.total = QtWidgets.QLabel(self.centralwidget)
        self.total.setAlignment(QtCore.Qt.AlignCenter)
        self.total.setObjectName("total")
        self.stats_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.total)
        self.total_num = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.total_num.setFont(font)
        self.total_num.setAlignment(QtCore.Qt.AlignCenter)
        self.total_num.setObjectName("total_num")
        self.stats_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.total_num)
        self.profit = QtWidgets.QLabel(self.centralwidget)
        self.profit.setAlignment(QtCore.Qt.AlignCenter)
        self.profit.setObjectName("profit")
        self.stats_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.profit)
        self.profit_num = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.profit_num.setFont(font)
        self.profit_num.setAlignment(QtCore.Qt.AlignCenter)
        self.profit_num.setObjectName("profit_num")
        self.stats_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.profit_num)
        self.loss = QtWidgets.QLabel(self.centralwidget)
        self.loss.setAlignment(QtCore.Qt.AlignCenter)
        self.loss.setObjectName("loss")
        self.stats_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.loss)
        self.loss_num = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.loss_num.setFont(font)
        self.loss_num.setAlignment(QtCore.Qt.AlignCenter)
        self.loss_num.setObjectName("loss_num")
        self.stats_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.loss_num)
        self.no_change = QtWidgets.QLabel(self.centralwidget)
        self.no_change.setAlignment(QtCore.Qt.AlignCenter)
        self.no_change.setObjectName("no_change")
        self.stats_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.no_change)
        self.no_change_num = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.no_change_num.setFont(font)
        self.no_change_num.setAlignment(QtCore.Qt.AlignCenter)
        self.no_change_num.setObjectName("no_change_num")
        self.stats_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.no_change_num)
        self.gridLayout_2.addLayout(self.stats_layout, 0, 1, 1, 1)
        self.buttons_layout = QtWidgets.QVBoxLayout()
        self.buttons_layout.setContentsMargins(10, 10, 10, 10)
        self.buttons_layout.setObjectName("buttons_layout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.buttons_layout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.buttons_layout.addItem(spacerItem1)
        self.status_layout = QtWidgets.QHBoxLayout()
        self.status_layout.setContentsMargins(5, 5, 5, 5)
        self.status_layout.setSpacing(10)
        self.status_layout.setObjectName("status_layout")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setObjectName("status")
        self.status_layout.addWidget(self.status)
        self.connection = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.connection.setFont(font)
        self.connection.setAlignment(QtCore.Qt.AlignCenter)
        self.connection.setObjectName("connection")
        self.status_layout.addWidget(self.connection)
        self.buttons_layout.addLayout(self.status_layout)
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setObjectName("start_button")
        self.buttons_layout.addWidget(self.start_button)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setObjectName("stop_button")
        self.buttons_layout.addWidget(self.stop_button)
        self.gridLayout_2.addLayout(self.buttons_layout, 1, 1, 1, 1)
        self.price_table = QtWidgets.QTableWidget(self.centralwidget)
        self.price_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.price_table.setObjectName("price_table")
        self.price_table.setColumnCount(8)
        self.price_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.price_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.price_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.price_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.price_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.price_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.price_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.price_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.price_table.setHorizontalHeaderItem(7, item)
        self.price_table.horizontalHeader().setStretchLastSection(True)
        self.price_table.verticalHeader().setVisible(False)
        self.price_table.verticalHeader().setDefaultSectionSize(25)
        self.price_table.verticalHeader().setMinimumSectionSize(25)
        self.gridLayout_2.addWidget(self.price_table, 0, 0, 2, 1)
        AppMainWindow.setCentralWidget(self.centralwidget)
        self.status_bar = QtWidgets.QStatusBar(AppMainWindow)
        self.status_bar.setObjectName("status_bar")
        AppMainWindow.setStatusBar(self.status_bar)

        self.retranslateUi(AppMainWindow)
        QtCore.QMetaObject.connectSlotsByName(AppMainWindow)

    def retranslateUi(self, AppMainWindow):
        _translate = QtCore.QCoreApplication.translate
        AppMainWindow.setWindowTitle(_translate("AppMainWindow", "Top Grossing Equity Securities - NSE, India"))
        self.total.setText(_translate("AppMainWindow", "Total"))
        self.total_num.setText(_translate("AppMainWindow", "0"))
        self.profit.setText(_translate("AppMainWindow", "Profit"))
        self.profit_num.setText(_translate("AppMainWindow", "0"))
        self.loss.setText(_translate("AppMainWindow", "Loss"))
        self.loss_num.setText(_translate("AppMainWindow", "0"))
        self.no_change.setText(_translate("AppMainWindow", "No Change"))
        self.no_change_num.setText(_translate("AppMainWindow", "0"))
        self.status.setText(_translate("AppMainWindow", "Status:"))
        self.connection.setText(_translate("AppMainWindow", "Unknown"))
        self.start_button.setText(_translate("AppMainWindow", "Start"))
        self.stop_button.setText(_translate("AppMainWindow", "Stop"))
        item = self.price_table.horizontalHeaderItem(0)
        item.setText(_translate("AppMainWindow", "Symbol"))
        item = self.price_table.horizontalHeaderItem(1)
        item.setText(_translate("AppMainWindow", "Last Price"))
        item = self.price_table.horizontalHeaderItem(2)
        item.setText(_translate("AppMainWindow", "Open"))
        item = self.price_table.horizontalHeaderItem(3)
        item.setText(_translate("AppMainWindow", "High"))
        item = self.price_table.horizontalHeaderItem(4)
        item.setText(_translate("AppMainWindow", "Low"))
        item = self.price_table.horizontalHeaderItem(5)
        item.setText(_translate("AppMainWindow", "Points"))
        item = self.price_table.horizontalHeaderItem(6)
        item.setText(_translate("AppMainWindow", "New Column"))
        item = self.price_table.horizontalHeaderItem(7)
        item.setText(_translate("AppMainWindow", "Volume"))
