# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppMainWindow(object):
    def setupUi(self, AppMainWindow):
        AppMainWindow.setObjectName("AppMainWindow")
        AppMainWindow.resize(1150, 480)
        AppMainWindow.setMinimumSize(QtCore.QSize(940, 480))
        self.centralwidget = QtWidgets.QWidget(AppMainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1024, 434))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.tableVertLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.tableVertLayout.setContentsMargins(0, 0, 0, 0)
        self.tableVertLayout.setObjectName("tableVertLayout")
        self.priceTable = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.priceTable.setMinimumSize(QtCore.QSize(1022, 370))
        self.priceTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.priceTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.priceTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.priceTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.priceTable.setRowCount(0)
        self.priceTable.setObjectName("priceTable")
        self.priceTable.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.priceTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.priceTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.priceTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.priceTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.priceTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.priceTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.priceTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.priceTable.setHorizontalHeaderItem(7, item)
        self.priceTable.horizontalHeader().setVisible(True)
        self.priceTable.verticalHeader().setVisible(False)
        self.priceTable.verticalHeader().setDefaultSectionSize(25)
        self.priceTable.verticalHeader().setMinimumSectionSize(25)
        self.tableVertLayout.addWidget(self.priceTable)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1040, 10, 101, 95))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.statsVertLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.statsVertLayout.setContentsMargins(0, 0, 0, 0)
        self.statsVertLayout.setObjectName("statsVertLayout")
        self.row0HorizLayout = QtWidgets.QHBoxLayout()
        self.row0HorizLayout.setObjectName("row0HorizLayout")
        self.totalStatic = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.totalStatic.setAlignment(QtCore.Qt.AlignCenter)
        self.totalStatic.setObjectName("totalStatic")
        self.row0HorizLayout.addWidget(self.totalStatic)
        self.total = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.total.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.total.setObjectName("total")
        self.row0HorizLayout.addWidget(self.total)
        self.statsVertLayout.addLayout(self.row0HorizLayout)
        self.row1HorizLayout = QtWidgets.QHBoxLayout()
        self.row1HorizLayout.setObjectName("row1HorizLayout")
        self.profitStatic = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.profitStatic.setAlignment(QtCore.Qt.AlignCenter)
        self.profitStatic.setObjectName("profitStatic")
        self.row1HorizLayout.addWidget(self.profitStatic)
        self.profit = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.profit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.profit.setObjectName("profit")
        self.row1HorizLayout.addWidget(self.profit)
        self.statsVertLayout.addLayout(self.row1HorizLayout)
        self.row2HorizLayout = QtWidgets.QHBoxLayout()
        self.row2HorizLayout.setObjectName("row2HorizLayout")
        self.lossStatic = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lossStatic.setAlignment(QtCore.Qt.AlignCenter)
        self.lossStatic.setObjectName("lossStatic")
        self.row2HorizLayout.addWidget(self.lossStatic)
        self.loss = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.loss.setFont(font)
        self.loss.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.loss.setObjectName("loss")
        self.row2HorizLayout.addWidget(self.loss)
        self.statsVertLayout.addLayout(self.row2HorizLayout)
        self.row3HorizLayout = QtWidgets.QHBoxLayout()
        self.row3HorizLayout.setObjectName("row3HorizLayout")
        self.noChangeStatic = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.noChangeStatic.setAlignment(QtCore.Qt.AlignCenter)
        self.noChangeStatic.setObjectName("noChangeStatic")
        self.row3HorizLayout.addWidget(self.noChangeStatic)
        self.noChange = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.noChange.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.noChange.setObjectName("noChange")
        self.row3HorizLayout.addWidget(self.noChange)
        self.statsVertLayout.addLayout(self.row3HorizLayout)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(1040, 350, 101, 91))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.buttonsVertLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.buttonsVertLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonsVertLayout.setObjectName("buttonsVertLayout")
        self.status = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setObjectName("status")
        self.buttonsVertLayout.addWidget(self.status)
        self.startFetch = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.startFetch.setMinimumSize(QtCore.QSize(50, 28))
        self.startFetch.setAutoRepeat(False)
        self.startFetch.setAutoRepeatDelay(1)
        self.startFetch.setAutoRepeatInterval(1)
        self.startFetch.setObjectName("startFetch")
        self.buttonsVertLayout.addWidget(self.startFetch)
        self.stopFetch = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.stopFetch.setMinimumSize(QtCore.QSize(75, 28))
        self.stopFetch.setObjectName("stopFetch")
        self.buttonsVertLayout.addWidget(self.stopFetch)
        AppMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AppMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1150, 26))
        self.menubar.setObjectName("menubar")
        AppMainWindow.setMenuBar(self.menubar)

        self.retranslateUi(AppMainWindow)
        QtCore.QMetaObject.connectSlotsByName(AppMainWindow)

    def retranslateUi(self, AppMainWindow):
        _translate = QtCore.QCoreApplication.translate
        AppMainWindow.setWindowTitle(_translate("AppMainWindow", "Top Grossing Equity Stocks - NSE, India"))
        item = self.priceTable.horizontalHeaderItem(0)
        item.setText(_translate("AppMainWindow", "Symbol"))
        item = self.priceTable.horizontalHeaderItem(1)
        item.setText(_translate("AppMainWindow", "Last Price"))
        item = self.priceTable.horizontalHeaderItem(2)
        item.setText(_translate("AppMainWindow", "Open"))
        item = self.priceTable.horizontalHeaderItem(3)
        item.setText(_translate("AppMainWindow", "High"))
        item = self.priceTable.horizontalHeaderItem(4)
        item.setText(_translate("AppMainWindow", "Low"))
        item = self.priceTable.horizontalHeaderItem(5)
        item.setText(_translate("AppMainWindow", "% Change"))
        item = self.priceTable.horizontalHeaderItem(6)
        item.setText(_translate("AppMainWindow", "Points Change"))
        item = self.priceTable.horizontalHeaderItem(7)
        item.setText(_translate("AppMainWindow", "Volume"))
        self.totalStatic.setText(_translate("AppMainWindow", "Total"))
        self.total.setText(_translate("AppMainWindow", "0"))
        self.profitStatic.setText(_translate("AppMainWindow", "Profit"))
        self.profit.setText(_translate("AppMainWindow", "0"))
        self.lossStatic.setText(_translate("AppMainWindow", "Loss"))
        self.loss.setText(_translate("AppMainWindow", "0"))
        self.noChangeStatic.setText(_translate("AppMainWindow", "No Chg"))
        self.noChange.setText(_translate("AppMainWindow", "0"))
        self.status.setText(_translate("AppMainWindow", "Status"))
        self.startFetch.setText(_translate("AppMainWindow", "Start"))
        self.stopFetch.setText(_translate("AppMainWindow", "Stop"))
